# parameters.yaml contains all of the options available for configuring the cepton_publisher node.
# You may copy/paste this into your own yaml file, or modify as needed.
# TLDR: run
#   ros2 run cepton_publisher cepton_publisher_node --ros-args --params-file /path/to/this/yaml/file

# These parameters will be applied to a node launched with name `cepton_publisher`
/cepton_publisher:
  ros__parameters:
    capture_file: ""
    capture_loop: true
    sensor_network_sources: ["0.0.0.0:8808"]
    cepx_output_type: BOTH
    pcl2_output_type: BOTH
    include_saturated_points: true
    include_second_return_points: false # set to false if second return mode is not enabled from firmware
    include_invalid_points: true
    include_noise_points: true
    include_blocked_points: true
    include_retro_points: true
    include_retro_weak_points: true
    include_ambient_points: false # set to false if ambient mode is not enabled from firmware
    min_altitude: -90.0
    max_altitude: 90.0
    min_azimuth: -90.0
    max_azimuth: 90.0
    max_distance: 1000.0
    min_distance: 0.0
    aggregation_frame_count: 1 # 1 disables aggregation. Use 2-255 to aggregate frames.
    qos_reliability: default # default: point clouds use best_effort, info/status use reliable. Other values: reliable, best_effort
    qos_durability: volatile # volatile or transient_local
    qos_history: keep_last # keep_last or keep_all
    qos_points_depth: 50
    qos_info_depth: 10
    qos_status_depth: 5

    # If uncommented, this parameter must not be an empty list.
    # rclcpp cannot load empty lists properly, and this will throw an exception. https://github.com/ros2/rclcpp/issues/1955
    # Commenting this out means that sensors will be discovered lazily, as they come online.
    #expected_sensor_ips: ["192.168.32.32"]

/cepton_subscriber:
  ros__parameters:
    subscribe_pcl2: true
    subscribe_cepton_info: true
    export_to_csv: false
    qos_reliability: default # default: point clouds use best_effort, info uses reliable. Other values: reliable, best_effort
    qos_durability: volatile # volatile or transient_local
    qos_history: keep_last # keep_last or keep_all
    qos_points_depth: 10
    qos_info_depth: 10
