# parameters.yaml contains all of the options available for configuring the cepton_publisher node.
# You may copy/paste this into your own yaml file, or modify as needed.
# TLDR: run
#   ros2 run cepton_publisher cepton_publisher_node --ros-args --params-file /path/to/this/yaml/file

# These parameters will be applied to a node launched with name `cepton_publisher`
/cepton_publisher:
  ros__parameters:
    capture_file: "/home/rkim/20250904_cepton_2.pcap"
    capture_loop: true
    sensor_port: 8808
    cepx_output_type: BOTH
    pcl2_output_type: BOTH
    include_saturated_points: true
    include_second_return_points: false
    include_invalid_points: false
    include_blocked_points: true
    include_ambient_points: true # set to false if ambient mode is not enabled from firmware
    min_altitude: -90.0
    max_altitude: 90.0
    min_azimuth: -90.0
    max_azimuth: 90.0
    max_distance: 1000.0
    min_distance: 0.0


    # If uncommented, this parameter must not be an empty list.
    # rclcpp cannot load empty lists properly, and this will throw an exception. https://github.com/ros2/rclcpp/issues/1955
    # Commenting this out means that sensors will be discovered lazily, as they come online.
    expected_sensor_ips: ["192.168.32.32"]
