name: ros-drivers

on:
  push:
    branches:
      - '**'


concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test-bindings:
    name: Test python SDK bindings
    runs-on:
      - self-hosted
      - Linux
      - X64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build . --tag ci_rust_$GITHUB_SHA -f ci/Dockerfile

      - name: Run tests
        run: |
            docker run --rm -v "${GITHUB_WORKSPACE}:/app:rw"  -v /mnt/jenkins/python-sdk-ci-test:/root/Documents/cepton ci_rust_$GITHUB_SHA bash -ex -c '
            cd ros2
            colcon build --packages-select cepton_messages cepton_subscriber cepton_publisher
            '