name: ros-drivers

on:
  push:
    branches:
      - '**'


jobs:
  build-driver:
    name: Build driver
    runs-on:
      - Linux
      - X64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build . --tag ci_rust_$GITHUB_SHA -f ci/Dockerfile

      - name: Run tests
        run: |
            docker run --rm -v "${GITHUB_WORKSPACE}:/app:rw" ci_rust_$GITHUB_SHA bash -ex -c '
            cd ros2
            colcon build --packages-select cepton_messages cepton_subscriber cepton_publisher
            '